version: 2

before:
  hooks:
    - go mod tidy
builds:
  - id: 'git-semv'
    main: ./cmd/git-semv
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - none*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - repository:
      owner: linyows
      name: homebrew-git-semv
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/linyows/git-semv
    description: This is a Git plugin for Semantic Versioning.
    license: "MIT"
    dependencies:
      - name: git
    install: |
      bin.install "git-semv"
      #  zsh_completion.install "misc/completion.zsh"
      #  bash_completion.install "misc/completion.bash"
      #  fish_completion.install "misc/completion.fish"
    test: |
      system "#{bin}/git-semv -v"
