name: Lint by GolangCI LInt
on:
  pull_request:
  schedule:
    - cron: |
        0 0 * * *
  push:
    tags:
      - v*
    branches:
      - main
jobs:
  golangci:
    name: GolongCI Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.25.x
      - uses: golangci/golangci-lint-action@v6
        with:
          version: latest
